# Generated by Django 5.1a1 on 2024-06-08 02:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiCasillero', '0004_create_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='impuesto_dai',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='impuesto_isc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='impuesto_ispc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='impuesto_isv',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
