# Generated by Django 5.2rc1 on 2025-03-26 22:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiCasillero', '0008_remove_partidaarancelaria_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='courier_category',
            field=models.CharField(choices=[('ALLOWED', 'Permitido para Courier'), ('RESTRICTED', 'Articulos restringidos para Courier'), ('PROHIBITED', 'Articulos prohibidos para Courier')], default='ALLOWED', max_length=20),
        ),
        migrations.AlterField(
            model_name='partidaarancelaria',
            name='search_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
