# Generated by Django 5.2rc1 on 2025-03-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0009_clean_search_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="search_keywords",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
