# Generated by Django 5.2.7 on 2025-10-18 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0015_add_search_vector_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="ai_confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="Nivel de confianza de la sugerencia seleccionada (0-1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="ai_suggested_partidas",
            field=models.JSONField(
                blank=True,
                help_text="Top 5 sugerencias del sistema AI: [{partida_id, score, reason}, ...]",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="correction_reason",
            field=models.TextField(
                blank=True, help_text="Razón de la corrección manual"
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="was_manually_corrected",
            field=models.BooleanField(
                default=False, help_text="¿Fue corregida manualmente por el personal?"
            ),
        ),
        migrations.CreateModel(
            name="ItemPartidaMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_description_original",
                    models.CharField(
                        help_text="Descripción del producto como aparece en la factura del cliente",
                        max_length=500,
                    ),
                ),
                (
                    "item_description_normalized",
                    models.CharField(
                        db_index=True,
                        help_text="Descripción normalizada (lowercase, sin caracteres especiales)",
                        max_length=500,
                    ),
                ),
                (
                    "item_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Vector embedding del item para búsqueda semántica",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0,
                        help_text="Nivel de confianza de la sugerencia AI (0-1)",
                    ),
                ),
                (
                    "ranking_position",
                    models.IntegerField(
                        default=1,
                        help_text="Posición en las sugerencias (1=primera sugerencia, 2=segunda, etc.)",
                    ),
                ),
                (
                    "was_ai_suggestion",
                    models.BooleanField(
                        default=True, help_text="¿Fue sugerido por el sistema AI?"
                    ),
                ),
                (
                    "is_staff_verified",
                    models.BooleanField(
                        default=False,
                        help_text="¿Seleccionado/verificado por personal administrativo?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key para usuarios anónimos",
                        max_length=40,
                    ),
                ),
                (
                    "staff_override",
                    models.BooleanField(
                        default=False, help_text="¿Fue corregido por el personal?"
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(blank=True, help_text="Razón de la corrección"),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partida_mapping",
                        to="MiCasillero.articulo",
                    ),
                ),
                (
                    "override_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Partida original antes de la corrección",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_mappings",
                        to="MiCasillero.partidaarancelaria",
                    ),
                ),
                (
                    "partida_arancelaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_mappings",
                        to="MiCasillero.partidaarancelaria",
                    ),
                ),
                (
                    "selected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partida_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeo Item-Partida",
                "verbose_name_plural": "Mapeos Item-Partida",
                "indexes": [
                    models.Index(
                        fields=["item_description_normalized"],
                        name="MiCasillero_item_de_0abf5a_idx",
                    ),
                    models.Index(
                        fields=["partida_arancelaria", "-created_at"],
                        name="MiCasillero_partida_1de049_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="MiCasillero_created_b889da_idx"
                    ),
                    models.Index(
                        fields=["is_staff_verified"],
                        name="MiCasillero_is_staf_730ba1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartidaArancelariaEmbedding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        help_text="Vector de embedding (1536 dimensiones)"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-3-small",
                        help_text="Modelo usado para generar el embedding",
                        max_length=50,
                    ),
                ),
                (
                    "embedding_text",
                    models.TextField(
                        help_text="Texto combinado: descripción + keywords + términos aprendidos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Versión del embedding, se incrementa con cada actualización",
                    ),
                ),
                (
                    "partida_arancelaria",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding_data",
                        to="MiCasillero.partidaarancelaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding de Partida",
                "verbose_name_plural": "Embeddings de Partidas",
                "indexes": [
                    models.Index(
                        fields=["partida_arancelaria"],
                        name="MiCasillero_partida_2bba51_idx",
                    ),
                    models.Index(
                        fields=["-updated_at"], name="MiCasillero_updated_7f0ed1_idx"
                    ),
                ],
            },
        ),
    ]
