# Generated by Django 5.2.7 on 2025-10-19 09:47

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0016_articulo_ai_confidence_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="envio",
            old_name="direccion_casillero",
            new_name="direccion_entrega",
        ),
        migrations.RemoveField(
            model_name="envio",
            name="flete",
        ),
        migrations.RemoveField(
            model_name="envio",
            name="tracking_number_final",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_expiracion",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 19, 9, 43, 54, 755535, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="session_key",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="subtotal_articulos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="total_estimado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="total_flete",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="total_impuestos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="envio",
            name="alto_real",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="envio",
            name="ancho_real",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="envio",
            name="factura_compra",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
        migrations.AddField(
            model_name="envio",
            name="fecha_entrega",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="envio",
            name="fecha_liberacion_aduana",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="envio",
            name="fecha_llegada_honduras",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="envio",
            name="fecha_recibido_miami",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="envio",
            name="fecha_salida_miami",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="envio",
            name="fecha_solicitud",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="envio",
            name="foto_paquete",
            field=models.ImageField(blank=True, null=True, upload_to="packages/"),
        ),
        migrations.AddField(
            model_name="envio",
            name="instrucciones_especiales",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="envio",
            name="largo_real",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="envio",
            name="peso_estimado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="envio",
            name="peso_real",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="envio",
            name="tracking_number_sicarga",
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Cotización Pendiente"),
                    ("Aceptada", "Aceptada - Envío Solicitado"),
                    ("Expirada", "Expirada"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="estado_envio",
            field=models.CharField(
                choices=[
                    ("Solicitado", "Solicitud Recibida"),
                    ("Recibido en Miami", "Recibido en Miami"),
                    ("Procesado", "Procesado y Listo para Envío"),
                    ("En tránsito a Honduras", "En Tránsito a Honduras"),
                    ("En aduana", "En Proceso de Aduana"),
                    ("Liberado de aduana", "Liberado de Aduana"),
                    ("En bodega local", "En Bodega Local"),
                    ("Disponible para entrega", "Disponible para Entrega"),
                    ("Entregado", "Entregado al Cliente"),
                ],
                default="Solicitado",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="StatusUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_anterior", models.CharField(blank=True, max_length=50)),
                ("estado_nuevo", models.CharField(max_length=50)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                ("ubicacion", models.CharField(blank=True, max_length=100)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="MiCasillero.envio",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
