# Generated by Django 5.2.7 on 2025-10-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "MiCasillero",
            "0017_rename_direccion_casillero_envio_direccion_entrega_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alerta",
            options={
                "ordering": ["-fecha_envio"],
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
            },
        ),
        migrations.AlterModelOptions(
            name="articulo",
            options={
                "ordering": ["id"],
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
            },
        ),
        migrations.AlterModelOptions(
            name="cotizacion",
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.AlterModelOptions(
            name="envio",
            options={
                "ordering": ["-fecha_solicitud"],
                "verbose_name": "Envío",
                "verbose_name_plural": "Envíos",
            },
        ),
        migrations.AlterModelOptions(
            name="factura",
            options={
                "ordering": ["-fecha_emision"],
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
            },
        ),
        migrations.AlterModelOptions(
            name="parametrosistema",
            options={
                "ordering": ["nombre_parametro"],
                "verbose_name": "Parámetro del Sistema",
                "verbose_name_plural": "Parámetros del Sistema",
            },
        ),
        migrations.AlterModelOptions(
            name="partidaarancelaria",
            options={
                "ordering": ["item_no"],
                "verbose_name": "Partida Arancelaria",
                "verbose_name_plural": "Partidas Arancelarias",
            },
        ),
        migrations.AlterModelOptions(
            name="statusupdate",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Actualización de Estado",
                "verbose_name_plural": "Actualizaciones de Estado",
            },
        ),
    ]
