# Generated by Django 5.2.7 on 2025-10-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0018_alter_alerta_options_alter_articulo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cotizacion",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
            },
        ),
    ]
