# Generated by Django 5.2.7 on 2025-10-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0019_alter_cotizacion_options"),
    ]

    operations = [
        # REMOVE the parent_category ForeignKey field (not useful for leaf nodes)
        migrations.RemoveField(
            model_name="partidaarancelaria",
            name="parent_category",
        ),
        # ADD hierarchy metadata fields
        migrations.AddField(
            model_name="partidaarancelaria",
            name="chapter_code",
            field=models.CharField(
                max_length=4,
                blank=True,
                null=True,
                help_text='First 4 digits of item_no (e.g., "0101", "8471")',
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="partidaarancelaria",
            name="heading_code",
            field=models.CharField(
                max_length=15,
                blank=True,
                null=True,
                help_text='Chapter + first subheading (e.g., "0101.21", "8471.30")',
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name="partidaarancelaria",
            name="parent_item_no",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text='Parent partida code in hierarchy (e.g., "0101.20.00.00" for "0101.21.00.00")',
            ),
        ),
        migrations.AddField(
            model_name="partidaarancelaria",
            name="grandparent_item_no",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="Grandparent partida code in hierarchy",
            ),
        ),
        migrations.AddField(
            model_name="partidaarancelaria",
            name="hierarchy_level",
            field=models.IntegerField(
                default=4,
                help_text="Depth in hierarchy: 1=chapter, 2=heading, 3=subheading, 4=leaf",
            ),
        ),
        migrations.AddField(
            model_name="partidaarancelaria",
            name="is_leaf_node",
            field=models.BooleanField(
                default=True,
                help_text="True if this is a leaf partida (has tax values)",
            ),
        ),
        # ADD indexes for efficient sibling queries
        migrations.AddIndex(
            model_name="partidaarancelaria",
            index=models.Index(fields=["chapter_code"], name="partida_chapter_idx"),
        ),
        migrations.AddIndex(
            model_name="partidaarancelaria",
            index=models.Index(fields=["heading_code"], name="partida_heading_idx"),
        ),
        migrations.AddIndex(
            model_name="partidaarancelaria",
            index=models.Index(fields=["hierarchy_level"], name="partida_level_idx"),
        ),
    ]
