# Generated by Django 5.2.7 on 2025-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0020_add_hierarchy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="chapter_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='First 4 digits (e.g., "0101", "8471")',
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="grandparent_item_no",
            field=models.CharField(
                blank=True,
                help_text="Grandparent partida code",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="heading_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Chapter + subheading (e.g., "0101.21", "8471.30")',
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="hierarchy_level",
            field=models.IntegerField(default=4, help_text="Hierarchy depth"),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="is_leaf_node",
            field=models.BooleanField(
                default=True, help_text="Leaf partida with tax values"
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="parent_item_no",
            field=models.CharField(
                blank=True, help_text="Parent partida code", max_length=50, null=True
            ),
        ),
    ]
