# Generated by Django 5.2.7 on 2025-10-28 20:53

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0021_alter_partidaarancelaria_chapter_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="envio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.envio",
                verbose_name="Envío",
            ),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="estado",
            field=models.CharField(
                choices=[("Enviado", "Enviado"), ("Error", "Error")],
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="fecha_envio",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Envío"
            ),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="mensaje",
            field=models.TextField(verbose_name="Mensaje"),
        ),
        migrations.AlterField(
            model_name="alerta",
            name="tipo_alerta",
            field=models.CharField(
                choices=[("SMS", "SMS"), ("WhatsApp", "WhatsApp")],
                max_length=50,
                verbose_name="Tipo de Alerta",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="ai_confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="Nivel de confianza de la sugerencia seleccionada (0-1)",
                null=True,
                verbose_name="Nivel de Confianza",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="ai_suggested_partidas",
            field=models.JSONField(
                blank=True,
                help_text="Top 5 sugerencias del sistema AI: [{partida_id, score, reason}, ...]",
                null=True,
                verbose_name="Sugerencias de Partidas por AI",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="alto",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Alto"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="ancho",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Ancho"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="correction_reason",
            field=models.TextField(
                blank=True,
                help_text="Razón de la corrección manual",
                verbose_name="Razón de la Corrección",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articulos",
                to="MiCasillero.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="descripcion_original",
            field=models.CharField(
                help_text="Descripción del producto según la factura de compra",
                max_length=255,
                verbose_name="Descripción Original",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="impuesto_dai",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Impuesto DAI",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="impuesto_isc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Impuesto ISC",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="impuesto_ispc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Impuesto ISPC",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="impuesto_isv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Impuesto ISV",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="impuesto_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Impuesto Total",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="largo",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Largo"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="partida_arancelaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.partidaarancelaria",
                verbose_name="Partida Arancelaria",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="peso",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Peso"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="valor_articulo",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor Artículo"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="was_manually_corrected",
            field=models.BooleanField(
                default=False,
                help_text="¿Fue corregida manualmente por el personal?",
                verbose_name="Corregida Manualmente",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="apellidos",
            field=models.CharField(max_length=255, verbose_name="Apellidos"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="ciudad",
            field=models.CharField(
                default="San Pedro Sula", max_length=50, verbose_name="Ciudad"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="codigo_cliente",
            field=models.CharField(
                max_length=13, unique=True, verbose_name="Código de Cliente"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="correo_electronico",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="departamento",
            field=models.CharField(
                default="Cortés", max_length=50, verbose_name="Departamento"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Registro"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombre_corto",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nombre Corto"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="nombres",
            field=models.CharField(max_length=255, verbose_name="Nombres"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="pais",
            field=models.CharField(
                default="Honduras", max_length=50, verbose_name="País"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(max_length=20, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Cotización Pendiente"),
                    ("Aceptada", "Aceptada - Envío Solicitado"),
                    ("Expirada", "Expirada"),
                ],
                default="Pendiente",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="fecha_expiracion",
            field=models.DateTimeField(verbose_name="Fecha de Expiración"),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Session Key"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="subtotal_articulos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Subtotal Artículos",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="total_estimado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Estimado",
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="total_flete",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total Flete"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="total_impuestos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Impuestos",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="alto_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Alto Real",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="ancho_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Ancho Real",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="cotizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.cotizacion",
                verbose_name="Cotización",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="direccion_entrega",
            field=models.CharField(max_length=255, verbose_name="Dirección de Entrega"),
        ),
        migrations.AlterField(
            model_name="envio",
            name="estado_envio",
            field=models.CharField(
                choices=[
                    ("Solicitado", "Solicitud Recibida"),
                    ("Recibido en Miami", "Recibido en Miami"),
                    ("Procesado", "Procesado y Listo para Envío"),
                    ("En tránsito a Honduras", "En Tránsito a Honduras"),
                    ("En aduana", "En Proceso de Aduana"),
                    ("Liberado de aduana", "Liberado de Aduana"),
                    ("En bodega local", "En Bodega Local"),
                    ("Disponible para entrega", "Disponible para Entrega"),
                    ("Entregado", "Entregado al Cliente"),
                ],
                default="Solicitado",
                max_length=50,
                verbose_name="Estado de Envío",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="factura_compra",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/",
                verbose_name="Factura de Compra",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Actualización"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="fecha_entrega",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Entrega"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="fecha_liberacion_aduana",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Liberación de Aduana"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="fecha_llegada_honduras",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Llegada a Honduras"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="fecha_recibido_miami",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Recepción en Miami"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="fecha_salida_miami",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Salida de Miami"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="fecha_solicitud",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Solicitud"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="foto_paquete",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="packages/",
                verbose_name="Foto del Paquete",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="instrucciones_especiales",
            field=models.TextField(blank=True, verbose_name="Instrucciones Especiales"),
        ),
        migrations.AlterField(
            model_name="envio",
            name="largo_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Largo Real",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="peso_estimado",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Peso Estimado"
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="peso_real",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Peso Real",
            ),
        ),
        migrations.AlterField(
            model_name="envio",
            name="tracking_number_original",
            field=models.CharField(max_length=50, verbose_name="Tracking No. Original"),
        ),
        migrations.AlterField(
            model_name="envio",
            name="tracking_number_sicarga",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Tracking No. Sicarga"
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="envio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MiCasillero.envio",
                verbose_name="Envío",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado_pago",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Pagada", "Pagada"),
                    ("Cancelada", "Cancelada"),
                ],
                max_length=20,
                verbose_name="Estado de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="fecha_emision",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Emisión"
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="flete",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Flete",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="monto_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto Total",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="total_impuesto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Impuesto",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="total_impuesto_dai",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Impuesto DAI",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="total_impuesto_isc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Impuesto ISC",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="total_impuesto_ispc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Impuesto ISPC",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="total_impuesto_isv",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Impuesto ISV",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                help_text="Artículo asociado a este mapeo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partida_mapping",
                to="MiCasillero.articulo",
                verbose_name="Artículo",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="confidence_score",
            field=models.FloatField(
                default=0,
                help_text="Nivel de confianza de la sugerencia AI (0-1)",
                verbose_name="Nivel de Confianza",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora de creación",
                verbose_name="Fecha de Creación",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="is_staff_verified",
            field=models.BooleanField(
                default=False,
                help_text="¿Seleccionado/verificado por personal administrativo?",
                verbose_name="Verificado por Staff",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="item_description_normalized",
            field=models.CharField(
                db_index=True,
                help_text="Descripción normalizada (lowercase, sin caracteres especiales)",
                max_length=500,
                verbose_name="Descripción Normalizada",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="item_description_original",
            field=models.CharField(
                help_text="Descripción del producto como aparece en la factura del cliente",
                max_length=500,
                verbose_name="Descripción Original",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="item_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Vector embedding del item para búsqueda semántica",
                null=True,
                verbose_name="Vector Embedding",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="override_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Partida original antes de la corrección",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overridden_mappings",
                to="MiCasillero.partidaarancelaria",
                verbose_name="Corrección de Partida",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="override_reason",
            field=models.TextField(
                blank=True,
                help_text="Razón de la corrección",
                verbose_name="Razón de la Corrección",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="partida_arancelaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_mappings",
                to="MiCasillero.partidaarancelaria",
                verbose_name="Partida Arancelaria",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="ranking_position",
            field=models.IntegerField(
                default=1,
                help_text="Posición en las sugerencias (1=primera sugerencia, 2=segunda, etc.)",
                verbose_name="Posición en Sugerencias",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="selected_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que seleccionó esta partida",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partida_selections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Seleccionado por",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Session key para usuarios anónimos",
                max_length=40,
                verbose_name="Session Key",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="staff_override",
            field=models.BooleanField(
                default=False,
                help_text="¿Fue corregido por el staff?",
                verbose_name="Corrección por Staff",
            ),
        ),
        migrations.AlterField(
            model_name="itempartidamapping",
            name="was_ai_suggestion",
            field=models.BooleanField(
                default=True,
                help_text="¿Fue sugerido por el sistema AI?",
                verbose_name="Sugerido por AI",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="chapter_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Primeros 4 dígitos (e.g., "0101", "8471")',
                max_length=4,
                null=True,
                verbose_name="Código de Capítulo",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="courier_category",
            field=models.CharField(
                choices=[
                    ("ALLOWED", "Permitido para Courier"),
                    ("RESTRICTED", "Articulos restringidos para Courier"),
                    ("PROHIBITED", "Articulos prohibidos para Courier"),
                ],
                default="ALLOWED",
                max_length=20,
                verbose_name="Categoría de Courier",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="descripcion",
            field=models.CharField(
                help_text="Partida | Partida Padre | Partida Abuelo",
                max_length=1255,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="grandparent_item_no",
            field=models.CharField(
                blank=True,
                help_text="Código de partida abuelo",
                max_length=50,
                null=True,
                verbose_name="Código de Partida Abuelo",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="heading_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Capítulo + subencabezado (e.g., "0101.21", "8471.30")',
                max_length=15,
                null=True,
                verbose_name="Código de Encabezado",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="hierarchy_level",
            field=models.IntegerField(
                default=4,
                help_text="Nivel de jerarquía (1=Capítulo, 2=Encabezado, 3=Subencabezado, 4=Partida detallada)",
                verbose_name="Nivel de Jerarquía",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="impuesto_dai",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Derechos Arancelarios a la Importación",
                max_digits=5,
                verbose_name="Impuesto DAI",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="impuesto_isc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Impuesto Selectivo al Consumo",
                max_digits=5,
                verbose_name="Impuesto ISC",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="impuesto_ispc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Impuesto Sobre Produccion y Consumo",
                max_digits=5,
                verbose_name="Impuesto ISPC",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="impuesto_isv",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Impuesto Sobre Ventas",
                max_digits=5,
                verbose_name="Impuesto ISV",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="is_leaf_node",
            field=models.BooleanField(
                default=True,
                help_text="Indica si es un nodo hoja (sin subpartidas)",
                verbose_name="¿Es de Último Nivel?",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="item_no",
            field=models.CharField(max_length=50, verbose_name="Item No"),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="max_weight_allowed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Peso Máximo Permitido",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="package_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tipo de Paquete"
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="parent_item_no",
            field=models.CharField(
                blank=True,
                help_text="Código de partida padre",
                max_length=50,
                null=True,
                verbose_name="Código de Partida Padre",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="partida_arancelaria",
            field=models.CharField(
                help_text="Código HS completo",
                max_length=50,
                verbose_name="Partida Arancelaria",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="requires_special_handling",
            field=models.BooleanField(
                default=False, verbose_name="Requiere Manejo Especial"
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="restrictions",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Restricciones"
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="search_keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Palabras clave para mejorar la búsqueda",
                null=True,
                verbose_name="Palabras Clave de Búsqueda",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                null=True, verbose_name="Vector de Búsqueda"
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="special_instructions",
            field=models.TextField(blank=True, verbose_name="Instrucciones Especiales"),
        ),
        migrations.AlterField(
            model_name="partidaarancelariaembedding",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelariaembedding",
            name="embedding_model",
            field=models.CharField(
                default="text-embedding-3-small",
                help_text="Modelo usado para generar el embedding",
                max_length=50,
                verbose_name="Modelo de Embedding",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelariaembedding",
            name="embedding_text",
            field=models.TextField(
                help_text="Texto combinado: descripción + keywords + términos aprendidos",
                verbose_name="Texto de Embedding",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelariaembedding",
            name="embedding_vector",
            field=models.JSONField(
                help_text="Vector de embedding (1536 dimensiones)",
                verbose_name="Vector de Embedding",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelariaembedding",
            name="partida_arancelaria",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding_data",
                to="MiCasillero.partidaarancelaria",
                verbose_name="Partida Arancelaria",
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelariaembedding",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Actualización"
            ),
        ),
        migrations.AlterField(
            model_name="partidaarancelariaembedding",
            name="version",
            field=models.IntegerField(
                default=1,
                help_text="Versión del embedding, se incrementa con cada actualización",
                verbose_name="Versión",
            ),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="actualizado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado Por",
            ),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="envio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="MiCasillero.envio",
                verbose_name="Envío",
            ),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="estado_anterior",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Estado Anterior"
            ),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="estado_nuevo",
            field=models.CharField(max_length=50, verbose_name="Estado Nuevo"),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="statusupdate",
            name="ubicacion",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Ubicación"
            ),
        ),
    ]
