# Generated by Django 5.2.7 on 2025-10-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiCasillero", "0022_alter_alerta_cliente_alter_alerta_envio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partidaarancelaria",
            name="impuesto_ispc",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Impuesto Sobre Produccción y Consumo",
                max_digits=5,
                verbose_name="Impuesto ISPC",
            ),
        ),
    ]
