# Generated by Django 5.2.7 on 2025-10-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiCasillero', '0023_alter_partidaarancelaria_impuesto_ispc'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosistema',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del parámetro y su propósito'),
        ),
    ]
