# Generated by Django 5.2.7 on 2025-10-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiCasillero', '0024_parametrosistema_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado_envio',
            field=models.CharField(choices=[('Solicitado', 'Solicitud Recibida'), ('Documentación Pendiente', 'Documentación Pendiente'), ('Recibido en Miami', 'Recibido en Miami'), ('Procesado', 'Procesado y Listo para Envío'), ('En tránsito a Honduras', 'En Tránsito a Honduras'), ('En aduana', 'En Proceso de Aduana'), ('Liberado de aduana', 'Liberado de Aduana'), ('En bodega local', 'En Bodega Local'), ('Disponible para entrega', 'Disponible para Entrega'), ('Entregado', 'Entregado al Cliente')], default='Solicitado', max_length=50, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del parámetro y su propósito', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='nombre_parametro',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Parámetro'),
        ),
        migrations.AlterField(
            model_name='parametrosistema',
            name='tipo_dato',
            field=models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean')], max_length=10, verbose_name='Tipo de Dato'),
        ),
    ]
