services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.5
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      node.name: "es01"
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      # Dev only: disable security so you can access ES without TLS/auth. Remove in prod.
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://127.0.0.1:9200/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data:
